url: "https://www.gospeldesk.org"
sass:
  sass_dir: .
exclude:
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "bin"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      html_title_sep: "-"
      clip_bottom: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      clip_bottom: false
collections:
  posts:
    permalink: "/:year/:title/"

plugins:
  - jekyll-feed

# For RSS feed, keep in sync with index.html meta
title: Gospel Desk
excerpt: "An Orthodox Christian Blog"
author: Chad Whitacre
